[package]
name = "cch23-tabulatejarl8"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
fancy-regex = "0.12.0"
rocket = {version = "0.5.0", features = ["json"]}
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
